/**
 * This class is generated by jOOQ
 */
package com.ormanli.duplicatefinder.db.public_;

/**
 * Convenience access to all tables in PUBLIC
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table PUBLIC.FILES
	 */
	public static final com.ormanli.duplicatefinder.db.public_.tables.Files FILES = com.ormanli.duplicatefinder.db.public_.tables.Files.FILES;
}
